config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'storehouses#index'

  resources :storehouses, only: %i[index new create] do
    resources :products, only: %i[index new create destroy]
  end

  resources :exchanges, only: %i[index new create] do
    collection do
      post :prepare_products
    end
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/exchange_history.rb
# frozen_string_literal: true

class ExchangeHistory < ApplicationRecord
  belongs_to :products_storehouse
  belongs_to :product
end

app/models/product.rb
# frozen_string_literal: true

class Product < ApplicationRecord
  belongs_to :storehouse
end

app/models/products_storehouse.rb
# frozen_string_literal: true

# Общепринятый нейминг для связей many-to-many здесь ради того, чтобы показать :) Так бы я по-другому назвал
class ProductsStorehouse < ApplicationRecord
  belongs_to :source_storehouse, class_name: 'Storehouse'
  belongs_to :target_storehouse, class_name: 'Storehouse'

  has_many :exchange_histories, dependent: :destroy, inverse_of: 'products_storehouse'

  validates :exchange_histories, length: { minimum: 1 }

  def process_products(products: {})
    products.each do |id, amount|
      ActiveRecord::Base.transaction do
        product = source_storehouse.products.find_by(id: id.to_i)
        next if product.amount < amount['amount'].to_i || amount['amount'].to_i.zero?

        product.amount -= amount['amount'].to_i
        target_product = target_storehouse.products.find_by(name: product.name) ||
                         target_storehouse.products.new(name: product.name)
        target_product.amount += amount['amount'].to_i
        history = exchange_histories.new(product_id: id.to_i, amount: amount['amount'])
        history.save
        target_product.save
        product.save
      end
    end
  end
end

app/models/storehouse.rb
# frozen_string_literal: true

class Storehouse < ApplicationRecord
  has_many :products, dependent: :destroy
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/exchanges_controller.rb
# frozen_string_literal: true

class ExchangesController < ApplicationController
  def index
    @exchanges = ProductsStorehouse.includes(:exchange_histories)
  end

  def new
    @exchange = ProductsStorehouse.new
  end

  def create
    @exchange = ProductsStorehouse.new(permitted_params[:storehouse])
    @exchange.process_products(products: permitted_params[:products])

    if @exchange.save
      redirect_to exchanges_path
    else
      head :unprocessable_entity
    end
  end

  def prepare_products
    @exchange = Storehouse.where(
      id: [prepare_params[:source_storehouse_id], prepare_params[:target_storehouse_id]]
    )
  end

  private

  def prepare_params
    params.require(:products_storehouse).permit(:source_storehouse_id, :target_storehouse_id)
  end

  def permitted_params
    {}.tap do |hash|
      hash[:storehouse] = params.require(:storehouse).permit(:source_storehouse_id, :target_storehouse_id)
      hash[:products] = params.require(:products).permit!
    end
  end
end

app/controllers/products_controller.rb
# frozen_string_literal: true

class ProductsController < ApplicationController
  before_action :find_storehouse, only: %i[index new create]

  def index
    @products = @storehouse.products
  end

  def new
    @product = @storehouse.products.new
  end

  def create
    @product = @storehouse.products.new(permitted_params)

    if @product.save
      redirect_to storehouse_products_path
    else
      head :unprocessable_entity
    end
  end

  def destroy
    @product = Product.find_by(id: params[:id])
    @product.destroy
  end

  private

  def find_storehouse
    @storehouse = Storehouse.find_by(id: params[:storehouse_id])
  end

  def permitted_params
    params.require(:product).permit(:name)
  end
end

app/controllers/storehouses_controller.rb
# frozen_string_literal: true

class StorehousesController < ApplicationController
  def index
    @storehouses = Storehouse.all
  end

  def new
    @storehouse = Storehouse.new
  end

  def create
    @storehouse = Storehouse.new(permitted_params)

    if @storehouse.save
      redirect_to storehouses_path
    else
      head :unprocessable_entity
    end
  end

  private

  def permitted_params
    params.require(:storehouse).permit(:name)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/exchange_histories/_exchange_history.html.erb
<%= exchange_history.product.name %> -- <%= exchange_history.amount %>;<br>

app/views/exchanges/_form.html.erb
<%= form_with model: @exchange, url: url_for(controller: 'exchanges', action: :create), local: false do |f| %>
  <table>
    <thead>
      <tr>
        <th>Name</th>
        <th>Sourse Storehouse Amount</th>
        <th>Amount to exchange</th>
        <th>Target Storehouse Amount</th>
      </tr>
    </thead>
    <tbody>
      <% @exchange.first.products.each do |product| %>
        <tr>
          <td><%= product.name %></td>
          <td>
            <%= product.amount %>
            <%= f.hidden_field :source_storehouse_id, value: @exchange.first.id %>
          </td>
          <td>
            <%= fields_for "products[]", product do |am| %>
              <%= am.number_field :amount %>
            <% end %>
          </td>
          <td>
            <%= @exchange.last.products.find_by(name: product.name)&.amount || 0 %>
            <%= f.hidden_field :target_storehouse_id, value: @exchange.last.id %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <%= f.submit 'Exchange' %>
<% end %>

app/views/exchanges/_products.html.erb
<tr>
</tr>

app/views/exchanges/index.html.erb
<h1>Exchange History</h1>
<%= link_to 'Main Page', '/' %>

<table>
  <thead>
    <tr>
      <th>Source Storehouse</th>
      <th>Target Storehouse</th>
      <th>Amount Exchanged</th>
      <th>Timestamp</th>
    </tr>
  </thead>
  <tbody>
    <%= render @exchanges %>
  </tbody>
</table>

app/views/exchanges/new.html.erb
<h1><%= link_to 'Exchange History', exchanges_path %></h1>
<h1>Select storehouses to exchange products</h1>

<div class="storehouses-form">
  <%= form_with model: @exchange, url: prepare_products_exchanges_path, local: false do |f| %>
    <div class="exchange-errors red hidden">
      <p>You must select different storehouses before continuing</p>
    </div>

    <div>
      <p>
        <%= f.label :source_storehouse_id %>
        <%= f.collection_select :source_storehouse_id, Storehouse.all, :id, :name, prompt: true %>
      </p>

      <p>
        <%= f.label :target_storehouse_id %>
        <%= f.collection_select :target_storehouse_id, Storehouse.all, :id, :name, prompt: true %>
      </p>

      <%= f.submit 'Select products' %>
    </div>

  <% end %>
</div>

app/views/exchanges/prepare_products.js.erb
document.querySelector('.storehouses-form').innerHTML = '<div><%= j render 'exchanges/form' %></div>'

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Warehouse</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/products/_product.html.erb
<div id="product-<%= product.id %>">
  <%= product.name %><%= button_to 'Delete',
                               storehouse_product_path(@storehouse, product),
                               method: :delete, remote: true %>
</div>
<br>

app/views/products/destroy.js.erb
$("#product-<%= @product.id %>").remove();

app/views/products/index.html.erb
<h1>Products</h1>

<div class="products">
  <%= render @products %>
</div>
<%= link_to 'New Product', new_storehouse_product_path %>
<%= link_to 'Back', storehouses_path %>

app/views/products/new.html.erb
<%= form_with  model: [@storehouse, @product] do |form| %>
  <p>
    <%= form.label :name %><br>
    <%= form.text_field :name, id: :storehouse_name %>
  </p><br>

  <p>
    <%= form.submit %>
  </p>

<% end %>

app/views/products_storehouses/_products_storehouse.html.erb
<tr>
  <td><%= products_storehouse.source_storehouse.name %></td>
  <td><%= products_storehouse.target_storehouse.name %></td>
  <td><%= render products_storehouse.exchange_histories %></td>
  <td><%= products_storehouse.created_at %></td>
</tr>

app/views/storehouses/_storehouse.html.erb
<%= link_to storehouse.name.capitalize, storehouse_products_path(storehouse) %>

<br>

app/views/storehouses/index.html.erb
<h2><%= link_to 'Exchange Products', new_exchange_path %></h2>
<h1>Storehouses</h1>

<%= render @storehouses %>

app/views/storehouses/new.html.erb
<%= form_with  model: @storehouse do |form| %>
  <p>
    <%= form.label :name %><br>
    <%= form.text_field :name, id: :storehouse_name %>
  </p><br>

  <p>
    <%= form.submit %>
  </p>

<% end %>